services:
# chown vomlume bind mode 
  init-chown-volumes:
    image: busybox
    command: ["sh", "-c", "chown -R ${UID:-0}:${GID:-0} /app/log"]
    volumes:
      - ./log:/app/log/
    user: root
    env_file:
      - .env
    init: true
# service app
  mc-data-manger:
    depends_on:
      - init-chown-volumes
    build:
      context: .
      dockerfile: Dockerfile  
      args:
        UID: ${UID:-0}
        GID: ${GID:-0}
        USER: ${USER_NAME:-root}
        GROUP: ${GROUP_NAME:-root}
        WEB_DIR : ${WEB_DIR:-/web}
        APP_HOME: /app
    tty: true
    ports:
      - "3300:3300"
    restart : always
    volumes:
      - ./data:/app/data/
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

##################
##   OPTIONAL   ##
##################
    ## OPTIONAL LOGGING SETTINGS
    # logging:
    #   driver: "json-file"
    #   options:
    #     max-size: "5m"      # max-size each log file
    #     max-file: "10"      # max-index, log files

    ## OPTIONAL RESOURCE LIMITS
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "2.0"      # Capacity CPU : 2.0 (100% of a Dual CPU core)
    #       memory: "1024M"    # Capacity Mem : 1024MB
    #     reservations:
    #       cpus: "0.5"      # allocated CPU: 0.25 (25% of a single CPU core)
    #       memory: "512M"    # allocated Mem: 256MB