basePath: /
definitions:
  controllers.GenDataParams:
    properties:
      accessKey:
        type: string
      bucket:
        type: string
      checkCSV:
        type: string
      checkGIF:
        type: string
      checkJSON:
        type: string
      checkPNG:
        type: string
      checkSQL:
        type: string
      checkServerJSON:
        type: string
      checkServerSQL:
        type: string
      checkTXT:
        type: string
      checkXML:
        type: string
      checkZIP:
        type: string
      databaseName:
        type: string
      endpoint:
        type: string
      host:
        type: string
      password:
        type: string
      path:
        type: string
      port:
        type: string
      projectId:
        type: string
      provider:
        type: string
      region:
        type: string
      secretKey:
        type: string
      sizeCSV:
        type: string
      sizeGIF:
        type: string
      sizeJSON:
        type: string
      sizePNG:
        type: string
      sizeSQL:
        type: string
      sizeServerJSON:
        type: string
      sizeServerSQL:
        type: string
      sizeTXT:
        type: string
      sizeXML:
        type: string
      sizeZIP:
        type: string
      username:
        type: string
    type: object
  models.BasicResponse:
    properties:
      Error:
        type: string
      Result:
        type: string
    type: object
info:
  contact:
    email: contact-to-cloud-barista@googlegroups.com
    name: API Support
    url: http://cloud-barista.github.io
  description: CM-DataMold REST API
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: CM-DataMold REST API
  version: latest
paths:
  /generate/dynamodb:
    post:
      consumes:
      - application/json
      description: Generate test data on AWS DynamoDB.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on AWS DynamoDB
      tags:
      - '[Test Data Generation] AWS DynamoDB'
  /generate/firestore:
    post:
      consumes:
      - application/json
      description: Generate test data on GCP Firestore.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      - description: Parameters required to generate test data
        in: formData
        name: CredentialGCP
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on GCP Firestore
      tags:
      - '[Test Data Generation] GCP Firestore'
  /generate/gcp:
    post:
      consumes:
      - application/json
      description: Generate test data on GCP Cloud Storage.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      - description: Parameters required to generate test data
        in: formData
        name: CredentialGCP
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on GCP Cloud Storage
      tags:
      - '[Test Data Generation] GCP Cloud Storage'
  /generate/linux:
    post:
      consumes:
      - application/json
      description: Generate test data on on-premise Linux.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "400":
          description: Invalid Request
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on on-premise Linux
      tags:
      - '[Test Data Generation] On-premise Linux'
  /generate/mongodb:
    post:
      consumes:
      - application/json
      description: Generate test data on NCP MongoDB.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on NCP MongoDB
      tags:
      - '[Test Data Generation] NCP MongoDB'
  /generate/mysql:
    post:
      consumes:
      - application/json
      description: Generate test data on MySQL.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on MySQL
      tags:
      - '[Test Data Generation] MySQL'
  /generate/ncp:
    post:
      consumes:
      - application/json
      description: Generate test data on NCP Object Storage.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on NCP Object Storage
      tags:
      - '[Test Data Generation] NCP Object Storage'
  /generate/s3:
    post:
      consumes:
      - application/json
      description: Generate test data on AWS S3.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on AWS S3
      tags:
      - '[Test Data Generation] AWS S3'
  /generate/windows:
    post:
      consumes:
      - application/json
      description: Generate test data on on-premise Windows.
      parameters:
      - description: Parameters required to generate test data
        in: body
        name: RequestBody
        required: true
        schema:
          $ref: '#/definitions/controllers.GenDataParams'
      produces:
      - application/json
      responses:
        "200":
          description: Successfully generated test data
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "400":
          description: Invalid Request
          schema:
            $ref: '#/definitions/models.BasicResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.BasicResponse'
      summary: Generate test data on on-premise Windows
      tags:
      - '[Test Data Generation] On-premise Windows'
swagger: "2.0"
