# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Golang CI

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main", "develop" ]
    paths-ignore:
      - '**.md'
      - '.gitignore'
      - 'LICENSE'

jobs:

  build:
    strategy:
      matrix:        
        go-version: ["1.21"]
        os: [ubuntu-20.04, windows-2022]
        #os: [ubuntu-22.04, ubuntu-20.04, windows-2022, windows-2019]        
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{matrix.go-version}}

    - name: Build
      run: go build -o cm-data-mold

    # - name: Test
    #   run: go test -v ./...
